In [1]:
import pandas as pd

In [3]:
data={'students':['rahman','oon','razak','mahadhir','abdullah','najib'],'marks':[85,None,65,75,None,55]}

In [5]:
df=pd.DataFrame(data)
df

   students  marks
0    rahman   85.0
1       oon    NaN
2     razak   65.0
3  mahadhir   75.0
4  abdullah    NaN
5     najib   55.0

In [6]:
print('Print Missing data')
print('Numbers of missing values :',df.isnull().sum())

Print Missing data
Numbers of missing values : students    0
marks       2
dtype: int64

In [7]:
avg_marks=df['marks'].mean()
print(avg_marks)

70.0

In [8]:
df.fillna(avg_marks,inplace=True)

In [9]:
print('after fillna() call')
df

after fillna() call

   students  marks
0    rahman   85.0
1       oon   70.0
2     razak   65.0
3  mahadhir   75.0
4  abdullah   70.0
5     najib   55.0

## Lets see how we will use in our project

In [10]:
students_data={'Names':['rahman','oon','razak','mahadhir','abdullah','najib'],'Marks':[85,None,65,75,None,55]}
df=pd.DataFrame(students_data)
print('Original Data')
df

Original Data

      Names  Marks
0    rahman   85.0
1       oon    NaN
2     razak   65.0
3  mahadhir   75.0
4  abdullah    NaN
5     najib   55.0

In [11]:
df.fillna(df['Marks'].mean(),inplace=True)
df

      Names  Marks
0    rahman   85.0
1       oon   70.0
2     razak   65.0
3  mahadhir   75.0
4  abdullah   70.0
5     najib   55.0

## dropna() example

In [12]:
students_data={'Names':['rahman','oon','razak','mahadhir','abdullah','najib'],'Marks':[85,None,65,75,None,55]}
df=pd.DataFrame(students_data)
df

      Names  Marks
0    rahman   85.0
1       oon    NaN
2     razak   65.0
3  mahadhir   75.0
4  abdullah    NaN
5     najib   55.0

In [15]:
df=df.dropna(subset=['Marks'])

In [16]:
print('Print Dataset after dropna()')
df

Print Dataset after dropna()

      Names  Marks
0    rahman   85.0
2     razak   65.0
3  mahadhir   75.0
5     najib   55.0

## Another Exmaple to use

In [45]:
emp_data={'Names':['rahman','oon','razak','mahadhir','abdullah','najib'],
          'Age':[35,None,25,20,24,None],
          'Salary':[50000,30000,20000,40000,None,None]}

In [46]:
df=pd.DataFrame(emp_data)
print('Original Data')
df

Original Data

      Names   Age   Salary
0    rahman  35.0  50000.0
1       oon   NaN  30000.0
2     razak  25.0  20000.0
3  mahadhir  20.0  40000.0
4  abdullah  24.0      NaN
5     najib   NaN      NaN

In [47]:
print('Numbers of missing values :',df.isnull().sum())

Numbers of missing values : Names     0
Age       2
Salary    2
dtype: int64

In [48]:
df_drop=df.dropna()
df_drop

      Names   Age   Salary
0    rahman  35.0  50000.0
2     razak  25.0  20000.0
3  mahadhir  20.0  40000.0

In [49]:
df_drop_salary=df.dropna(subset=['Salary'])
df_drop_salary

      Names   Age   Salary
0    rahman  35.0  50000.0
1       oon   NaN  30000.0
2     razak  25.0  20000.0
3  mahadhir  20.0  40000.0

In [58]:
df.fillna({'Age':df['Age'].mean(),'Salary':df['Salary'].mean()}, inplace=True)
df

      Names   Age   Salary
0    rahman  35.0  50000.0
1       oon  26.0  30000.0
2     razak  25.0  20000.0
3  mahadhir  20.0  40000.0
4  abdullah  24.0  35000.0
5     najib  26.0  35000.0

### Exercise

In [169]:
df=pd.read_csv('students_performance_dirty.csv')
df.head(5)

   gender  study_hours  attendance_pct  math_score  reading_score  final_score
0    male          1.7            83.6        62.0           91.0         38.9
1     NaN          2.6            91.2        82.0           60.0         37.5
2  female          2.9            97.5        69.0           57.0         35.0
3  female          4.8            85.7        78.0           62.0         36.5
4    male          3.9           -10.0        64.0           95.0         30.9

In [170]:
df.isnull().sum()

gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

In [171]:
dfs=df.dropna(subset=['gender']) 
dfs

,gender,study_hours,attendance_pct,math_score,reading_score,final_score
0,male,1.7,83.6,62.0,91.0,38.9
2,female,2.9,97.5,69.0,57.0,35.0
3,female,4.8,85.7,78.0,62.0,36.5
4,male,3.9,-10.0,64.0,95.0,30.9
5,male,1.4,93.7,77.0,72.0,39.0
6,male,NaN,87.1,95.0,78.0,43.4
7,femle,NaN,70.6,59.0,70.0,32.8
8,female,2.7,74.7,68.0,71.0,35.3
9,female,4.2,92.4,63.0,66.0,35.0
10,male,4.7,67.9,94.0,73.0,40.1
12,femle,NaN,95.0,59.0,92.0,39.7
13,male,NaN,86.5,61.0,50.0,30.8
14,male,3.9,79.0,68.0,91.0,39.8
15,male,4.7,76.5,58.0,78.0,34.9
16,male,2.9,93.2,64.0,68.0,35.7
17,female,3.3,89.7,72.0,65.0,36.5
18,female,2.2,150.0,68.0,85.0,45.6
19,male,2.1,95.7,82.0,75.0,41.0
20,female,NaN,93.5,65.0,54.0,33.1
21,male,5.1,102.9,67.0,76.0,38.9
22,male,3.4,90.7,74.0,86.0,41.0
23,male,4.7,83.4,104.0,82.0,45.5
24,female,3.9,83.6,58.0,64.0,32.9
25,female,2.7,65.7,99.0,56.0,37.5
26,male,3.9,86.5,52.0,68.0,32.7
27,female,5.3,84.8,73.0,111.0,45.4
28,female,NaN,71.7,65.0,53.0,30.8
29,male,5.4,84.7,58.0,62.0,32.4
30,female,0.4,98.4,80.0,77.0,41.3
31,male,4.5,77.7,79.0,71.0,37.7
32,male,3.6,75.4,63.0,70.0,34.0
35,femle,1.1,115.6,72.0,72.0,40.3
36,male,3.2,71.8,70.0,74.0,36.1
37,male,3.9,92.2,81.0,62.0,38.0
38,female,5.3,88.2,99.0,55.0,39.6
39,female,2.9,85.6,76.0,75.0,38.8
40,male,2.5,94.1,79.0,94.0,43.9
41,female,2.9,84.7,72.0,77.0,38.3
42,male,4.6,65.6,88.0,73.0,38.7
44,male,2.9,200.0,81.0,69.0,50.0
45,female,4.1,96.7,97.0,86.0,46.3
46,male,3.6,81.3,73.0,66.0,36.0
47,female,4.7,90.0,66.0,56.0,33.3
48,female,2.7,112.8,77.0,53.0,37.2
49,male,3.1,84.7,87.0,73.0,40.5
51,female,1.7,86.9,86.0,75.0,40.8
53,femle,3.8,81.5,57.0,78.0,35.0
54,female,3.5,91.1,62.0,74.0,36.3
56,male,1.8,88.4,72.0,88.0,40.8
57,male,3.0,85.5,64.0,61.0,33.4
58,male,3.1,82.8,88.0,44.0,34.8
59,male,NaN,80.2,51.0,68.0,31.7

In [176]:
dfg.fillna({'study_hours':dfs['study_hours'].mean()}, inplace=True)
dfg

,gender,study_hours,attendance_pct,math_score,reading_score,final_score
0,male,1.700000,83.6,62.0,91.0,38.9
2,female,2.900000,97.5,69.0,57.0,35.0
3,female,4.800000,85.7,78.0,62.0,36.5
4,male,3.900000,-10.0,64.0,95.0,30.9
5,male,1.400000,93.7,77.0,72.0,39.0
6,male,3.393333,87.1,95.0,78.0,43.4
7,femle,3.393333,70.6,59.0,70.0,32.8
8,female,2.700000,74.7,68.0,71.0,35.3
9,female,4.200000,92.4,63.0,66.0,35.0
10,male,4.700000,67.9,94.0,73.0,40.1
12,femle,3.393333,95.0,59.0,92.0,39.7
13,male,3.393333,86.5,61.0,50.0,30.8
14,male,3.900000,79.0,68.0,91.0,39.8
15,male,4.700000,76.5,58.0,78.0,34.9
16,male,2.900000,93.2,64.0,68.0,35.7
17,female,3.300000,89.7,72.0,65.0,36.5
18,female,2.200000,150.0,68.0,85.0,45.6
19,male,2.100000,95.7,82.0,75.0,41.0
20,female,3.393333,93.5,65.0,54.0,33.1
21,male,5.100000,102.9,67.0,76.0,38.9
22,male,3.400000,90.7,74.0,86.0,41.0
23,male,4.700000,83.4,104.0,82.0,45.5
24,female,3.900000,83.6,58.0,64.0,32.9
25,female,2.700000,65.7,99.0,56.0,37.5
26,male,3.900000,86.5,52.0,68.0,32.7
27,female,5.300000,84.8,73.0,111.0,45.4
28,female,3.393333,71.7,65.0,53.0,30.8
29,male,5.400000,84.7,58.0,62.0,32.4
30,female,0.400000,98.4,80.0,77.0,41.3
31,male,4.500000,77.7,79.0,71.0,37.7
32,male,3.600000,75.4,63.0,70.0,34.0
35,femle,1.100000,115.6,72.0,72.0,40.3
36,male,3.200000,71.8,70.0,74.0,36.1
37,male,3.900000,92.2,81.0,62.0,38.0
38,female,5.300000,88.2,99.0,55.0,39.6
39,female,2.900000,85.6,76.0,75.0,38.8
40,male,2.500000,94.1,79.0,94.0,43.9
41,female,2.900000,84.7,72.0,77.0,38.3
42,male,4.600000,65.6,88.0,73.0,38.7
44,male,2.900000,200.0,81.0,69.0,50.0
45,female,4.100000,96.7,97.0,86.0,46.3
46,male,3.600000,81.3,73.0,66.0,36.0
47,female,4.700000,90.0,66.0,56.0,33.3
48,female,2.700000,112.8,77.0,53.0,37.2
49,male,3.100000,84.7,87.0,73.0,40.5
51,female,1.700000,86.9,86.0,75.0,40.8
53,femle,3.800000,81.5,57.0,78.0,35.0
54,female,3.500000,91.1,62.0,74.0,36.3
56,male,1.800000,88.4,72.0,88.0,40.8
57,male,3.000000,85.5,64.0,61.0,33.4
58,male,3.100000,82.8,88.0,44.0,34.8
59,male,3.393333,80.2,51.0,68.0,31.7

In [173]:
dfg.isnull().sum()

gender            0
study_hours       0
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64