In [1]:
import pandas as pd

In [2]:
#Sample dataset
data = {
    'Name' : ['ali','sarah','johan',None,'zaid'],
    'Age' : [25,None,30,22,None],
    'City' :['KL','Penang',None,'Johor','KL']
}

In [3]:
df=pd.DataFrame(data)
print('Original Data Frame :')
print(df)

Original Data Frame :
    Name   Age    City
0    ali  25.0      KL
1  sarah   NaN  Penang
2  johan  30.0    None
3   None  22.0   Johor
4   zaid   NaN      KL

In [8]:
#check how many missing
df.isnull().sum()

Name    1
Age     2
City    1
dtype: int64

In [9]:
#Check missing in row
for index, row in df.iterrows():
    print(f'Row {index} : Missing ={row.isnull().any()}, Details={row.isnull().to_dict()}')

Row 0 : Missing =False, Details={'Name': False, 'Age': False, 'City': False}
Row 1 : Missing =True, Details={'Name': False, 'Age': True, 'City': False}
Row 2 : Missing =True, Details={'Name': False, 'Age': False, 'City': True}
Row 3 : Missing =True, Details={'Name': True, 'Age': False, 'City': False}
Row 4 : Missing =True, Details={'Name': False, 'Age': True, 'City': False}

In [11]:
#Show only rows with missing data
missing_rows = df[df.isnull().any(axis=1)]
print('Rows with missing data')
print(missing_rows)
print('Above rows will be drop using dropna()')

Rows with missing data
    Name   Age    City
1  sarah   NaN  Penang
2  johan  30.0    None
3   None  22.0   Johor
4   zaid   NaN      KL
Above rows will be drop using dropna()

In [26]:
#cleaned data with dropna()
df_cleaned = df.dropna()
print('nAfter dropna() data')
print(df_cleaned)

nAfter dropna() data
  Name   Age City
0  ali  25.0   KL

In [27]:
print('Before fillna()')
print(df)

Before fillna()
    Name   Age    City
0    ali  25.0      KL
1  sarah   NaN  Penang
2  johan  30.0    None
3   None  22.0   Johor
4   zaid   NaN      KL

In [28]:
df_filled = df.fillna({'Name':'Unknown',
                       'Age' : df['Age'].mean(),
                       'City': 'Not Available'})
#Data display after fillna()
print('\nAfter fillna()') 
print(df_filled)

After fillna()
      Name        Age           City
0      ali  25.000000             KL
1    sarah  25.666667         Penang
2    johan  30.000000  Not Available
3  Unknown  22.000000          Johor
4     zaid  25.666667             KL

In [30]:
#round at 1 decimal
df_fills = df.fillna({'Name':'Unknown',
                       'Age' : round(df['Age'].mean(),1),
                       'City': 'Not Available'})
print('\nAfter fillna() : 2 decimal')
print(df_fills)

After fillna() : 2 decimal
      Name   Age           City
0      ali  25.0             KL
1    sarah  25.7         Penang
2    johan  30.0  Not Available
3  Unknown  22.0          Johor
4     zaid  25.7             KL

In [33]:
import math

In [78]:
df_floor = df.fillna({
    'Name': 'Unknown',
    'Age': math.floor(df['Age'].mean().astype(int)),
    'City': 'Not Available'
})
print('\nAfter fillna() : a floor')
print(df_floor)

After fillna() : a floor
      Name   Age           City
0      ali  25.0             KL
1    sarah  25.0         Penang
2    johan  30.0  Not Available
3  Unknown  22.0          Johor
4     zaid  25.0             KL

In [79]:
df_new = df.fillna({
    'Name': 'Unknown',
    'Age': math.ceil(df['Age'].mean().astype(int)),
    'City': 'Not Available'
})
print('\nAfter fillna() : a ceilling')
print(df_new)

After fillna() : a ceilling
      Name   Age           City
0      ali  25.0             KL
1    sarah  25.0         Penang
2    johan  30.0  Not Available
3  Unknown  22.0          Johor
4     zaid  25.0             KL

## Exercise 1

In [80]:
import pandas as pd
import math

In [81]:
dt = pd.read_csv('students_performance_dirty.csv')
dt.head(2)

  gender  study_hours  attendance_pct  math_score  reading_score  final_score
0   male          1.7            83.6        62.0           91.0         38.9
1    NaN          2.6            91.2        82.0           60.0         37.5

In [82]:
dt.describe()

       study_hours  attendance_pct  math_score  reading_score  final_score
count    52.000000       60.000000   60.000000      60.000000    60.000000
mean      3.413462       91.411667   71.850000      72.433333    37.985000
std       1.125468       35.852150   13.316009      12.972418     4.813076
min       0.400000      -10.000000   39.000000      44.000000    30.800000
25%       2.850000       81.450000   63.000000      63.500000    34.875000
50%       3.450000       86.500000   71.000000      72.500000    37.500000
75%       4.125000       93.275000   79.250000      78.000000    40.350000
max       5.400000      300.000000  104.000000     111.000000    56.600000

In [83]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gender          52 non-null     object
 1   study_hours     52 non-null     float64
 2   attendance_pct  60 non-null     float64
 3   math_score      60 non-null     float64
 4   reading_score   60 non-null     float64
 5   final_score     60 non-null     float64
dtypes: float64(5), object(1)
memory usage: 2.9+ KB

In [65]:
dt.isnull().sum()

gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

In [75]:
for index, row in dt.iterrows():
    if row.isnull().any():
        print(f'Row {index} : Missing ={row.isnull().to_dict()}')

Row 1 : Missing ={'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 6 : Missing ={'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 7 : Missing ={'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 11 : Missing ={'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 12 : Missing ={'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 13 : Missing ={'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 20 : Missing ={'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 28 : Missing ={'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 33 : Missing ={'gender': True, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 34 : Missing ={'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 43 : Missing ={'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 50 : Missing ={'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 52 : Missing ={'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 55 : Missing ={'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 59 : Missing ={'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}

In [54]:
missing_rows = dt[dt.isnull().any(axis=1)]
print('Rows with missing data')
print(missing_rows)
print('Above rows will be drop using dropna()')

Rows with missing data
    gender  study_hours  attendance_pct  math_score  reading_score  \
1      NaN          2.6            91.2        82.0           60.0
6     male          NaN            87.1        95.0           78.0
7    femle          NaN            70.6        59.0           70.0
11     NaN          4.6            86.2        63.0           78.0
12   femle          NaN            95.0        59.0           92.0
13    male          NaN            86.5        61.0           50.0
20  female          NaN            93.5        65.0           54.0
28  female          NaN            71.7        65.0           53.0
33     NaN          NaN            96.0        39.0           96.0
34     NaN          3.6            91.3        64.0           62.0
43     NaN          3.9            76.5        78.0           73.0
50     NaN          3.0            84.9        78.0           85.0
52     NaN          3.9            91.1        60.0           68.0
55     NaN          3.2           300.0        51.0           82.0
59    male          NaN            80.2        51.0           68.0

    final_score
1          37.5
6          43.4
7          32.8
11         36.9
12         39.7
13         30.8
20         33.1
28         30.8
33         36.6
34         34.2
43         37.8
50         40.9
52         34.7
55         56.6
59         31.7
Above rows will be drop using dropna()

In [56]:
dt_cleaned = dt.dropna()
print('nAfter dropna() data')
print(dt_cleaned)

nAfter dropna() data
    gender  study_hours  attendance_pct  math_score  reading_score  \
0     male          1.7            83.6        62.0           91.0
2   female          2.9            97.5        69.0           57.0
3   female          4.8            85.7        78.0           62.0
4     male          3.9           -10.0        64.0           95.0
5     male          1.4            93.7        77.0           72.0
8   female          2.7            74.7        68.0           71.0
9   female          4.2            92.4        63.0           66.0
10    male          4.7            67.9        94.0           73.0
14    male          3.9            79.0        68.0           91.0
15    male          4.7            76.5        58.0           78.0
16    male          2.9            93.2        64.0           68.0
17  female          3.3            89.7        72.0           65.0
18  female          2.2           150.0        68.0           85.0
19    male          2.1            95.7        82.0           75.0
21    male          5.1           102.9        67.0           76.0
22    male          3.4            90.7        74.0           86.0
23    male          4.7            83.4       104.0           82.0
24  female          3.9            83.6        58.0           64.0
25  female          2.7            65.7        99.0           56.0
26    male          3.9            86.5        52.0           68.0
27  female          5.3            84.8        73.0          111.0
29    male          5.4            84.7        58.0           62.0
30  female          0.4            98.4        80.0           77.0
31    male          4.5            77.7        79.0           71.0
32    male          3.6            75.4        63.0           70.0
35   femle          1.1           115.6        72.0           72.0
36    male          3.2            71.8        70.0           74.0
37    male          3.9            92.2        81.0           62.0
38  female          5.3            88.2        99.0           55.0
39  female          2.9            85.6        76.0           75.0
40    male          2.5            94.1        79.0           94.0
41  female          2.9            84.7        72.0           77.0
42    male          4.6            65.6        88.0           73.0
44    male          2.9           200.0        81.0           69.0
45  female          4.1            96.7        97.0           86.0
46    male          3.6            81.3        73.0           66.0
47  female          4.7            90.0        66.0           56.0
48  female          2.7           112.8        77.0           53.0
49    male          3.1            84.7        87.0           73.0
51  female          1.7            86.9        86.0           75.0
53   femle          3.8            81.5        57.0           78.0
54  female          3.5            91.1        62.0           74.0
56    male          1.8            88.4        72.0           88.0
57    male          3.0            85.5        64.0           61.0
58    male          3.1            82.8        88.0           44.0

    final_score
0          38.9
2          35.0
3          36.5
4          30.9
5          39.0
8          35.3
9          35.0
10         40.1
14         39.8
15         34.9
16         35.7
17         36.5
18         45.6
19         41.0
21         38.9
22         41.0
23         45.5
24         32.9
25         37.5
26         32.7
27         45.4
29         32.4
30         41.3
31         37.7
32         34.0
35         40.3
36         36.1
37         38.0
38         39.6
39         38.8
40         43.9
41         38.3
42         38.7
44         50.0
45         46.3
46         36.0
47         33.3
48         37.2
49         40.5
51         40.8
53         35.0
54         36.3
56         40.8
57         33.4
58         34.8

In [70]:
print('Shape before dropna() :', dt.shape)
print('Shape after dropna() :', dt_cleaned.shape)

Shape before dropna() : (60, 6)
Shape after dropna() : (45, 6)

In [60]:
#Fill data in defined columns
dt_fills = dt.fillna({'gender':'Unknown',
                       'study_hours' : round(dt['study_hours'].mean(),1),
                       })
print('\nAfter fillna() : 1 decimal')
print(dt_fills)

After fillna() : 1 decimal
     gender  study_hours  attendance_pct  math_score  reading_score  \
0      male          1.7            83.6        62.0           91.0
1   Unknown          2.6            91.2        82.0           60.0
2    female          2.9            97.5        69.0           57.0
3    female          4.8            85.7        78.0           62.0
4      male          3.9           -10.0        64.0           95.0
5      male          1.4            93.7        77.0           72.0
6      male          3.4            87.1        95.0           78.0
7     femle          3.4            70.6        59.0           70.0
8    female          2.7            74.7        68.0           71.0
9    female          4.2            92.4        63.0           66.0
10     male          4.7            67.9        94.0           73.0
11  Unknown          4.6            86.2        63.0           78.0
12    femle          3.4            95.0        59.0           92.0
13     male          3.4            86.5        61.0           50.0
14     male          3.9            79.0        68.0           91.0
15     male          4.7            76.5        58.0           78.0
16     male          2.9            93.2        64.0           68.0
17   female          3.3            89.7        72.0           65.0
18   female          2.2           150.0        68.0           85.0
19     male          2.1            95.7        82.0           75.0
20   female          3.4            93.5        65.0           54.0
21     male          5.1           102.9        67.0           76.0
22     male          3.4            90.7        74.0           86.0
23     male          4.7            83.4       104.0           82.0
24   female          3.9            83.6        58.0           64.0
25   female          2.7            65.7        99.0           56.0
26     male          3.9            86.5        52.0           68.0
27   female          5.3            84.8        73.0          111.0
28   female          3.4            71.7        65.0           53.0
29     male          5.4            84.7        58.0           62.0
30   female          0.4            98.4        80.0           77.0
31     male          4.5            77.7        79.0           71.0
32     male          3.6            75.4        63.0           70.0
33  Unknown          3.4            96.0        39.0           96.0
34  Unknown          3.6            91.3        64.0           62.0
35    femle          1.1           115.6        72.0           72.0
36     male          3.2            71.8        70.0           74.0
37     male          3.9            92.2        81.0           62.0
38   female          5.3            88.2        99.0           55.0
39   female          2.9            85.6        76.0           75.0
40     male          2.5            94.1        79.0           94.0
41   female          2.9            84.7        72.0           77.0
42     male          4.6            65.6        88.0           73.0
43  Unknown          3.9            76.5        78.0           73.0
44     male          2.9           200.0        81.0           69.0
45   female          4.1            96.7        97.0           86.0
46     male          3.6            81.3        73.0           66.0
47   female          4.7            90.0        66.0           56.0
48   female          2.7           112.8        77.0           53.0
49     male          3.1            84.7        87.0           73.0
50  Unknown          3.0            84.9        78.0           85.0
51   female          1.7            86.9        86.0           75.0
52  Unknown          3.9            91.1        60.0           68.0
53    femle          3.8            81.5        57.0           78.0
54   female          3.5            91.1        62.0           74.0
55  Unknown          3.2           300.0        51.0           82.0
56     male          1.8            88.4        72.0           88.0
57     male          3.0            85.5        64.0           61.0
58     male          3.1            82.8        88.0           44.0
59     male          3.4            80.2        51.0           68.0

    final_score
0          38.9
1          37.5
2          35.0
3          36.5
4          30.9
5          39.0
6          43.4
7          32.8
8          35.3
9          35.0
10         40.1
11         36.9
12         39.7
13         30.8
14         39.8
15         34.9
16         35.7
17         36.5
18         45.6
19         41.0
20         33.1
21         38.9
22         41.0
23         45.5
24         32.9
25         37.5
26         32.7
27         45.4
28         30.8
29         32.4
30         41.3
31         37.7
32         34.0
33         36.6
34         34.2
35         40.3
36         36.1
37         38.0
38         39.6
39         38.8
40         43.9
41         38.3
42         38.7
43         37.8
44         50.0
45         46.3
46         36.0
47         33.3
48         37.2
49         40.5
50         40.9
51         40.8
52         34.7
53         35.0
54         36.3
55         56.6
56         40.8
57         33.4
58         34.8
59         31.7

In [74]:
print('Shape after fillna() :',dt_fills.shape)
print('Original Shape :', dt.shape)
print('Shape after dropna() :', dt_cleaned.shape)

Shape after fillna() : (60, 6)
Original Shape : (60, 6)
Shape after dropna() : (45, 6)

In [85]:
#comparing data row by row
for i in range(len(dt)):
    print(f'\nrow {i} Before : {dt.iloc[i].to_dict()}')
    print(f'row {i} After : {dt_fills.iloc[i].to_dict()}')

row 0 Before : {'gender': 'male', 'study_hours': 1.7, 'attendance_pct': 83.6, 'math_score': 62.0, 'reading_score': 91.0, 'final_score': 38.9}
row 0 After : {'gender': 'male', 'study_hours': 1.7, 'attendance_pct': 83.6, 'math_score': 62.0, 'reading_score': 91.0, 'final_score': 38.9}

row 1 Before : {'gender': nan, 'study_hours': 2.6, 'attendance_pct': 91.2, 'math_score': 82.0, 'reading_score': 60.0, 'final_score': 37.5}
row 1 After : {'gender': 'Unknown', 'study_hours': 2.6, 'attendance_pct': 91.2, 'math_score': 82.0, 'reading_score': 60.0, 'final_score': 37.5}

row 2 Before : {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 97.5, 'math_score': 69.0, 'reading_score': 57.0, 'final_score': 35.0}
row 2 After : {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 97.5, 'math_score': 69.0, 'reading_score': 57.0, 'final_score': 35.0}

row 3 Before : {'gender': 'female', 'study_hours': 4.8, 'attendance_pct': 85.7, 'math_score': 78.0, 'reading_score': 62.0, 'final_score': 36.5}
row 3 After : {'gender': 'female', 'study_hours': 4.8, 'attendance_pct': 85.7, 'math_score': 78.0, 'reading_score': 62.0, 'final_score': 36.5}

row 4 Before : {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': -10.0, 'math_score': 64.0, 'reading_score': 95.0, 'final_score': 30.9}
row 4 After : {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': -10.0, 'math_score': 64.0, 'reading_score': 95.0, 'final_score': 30.9}

row 5 Before : {'gender': 'male', 'study_hours': 1.4, 'attendance_pct': 93.7, 'math_score': 77.0, 'reading_score': 72.0, 'final_score': 39.0}
row 5 After : {'gender': 'male', 'study_hours': 1.4, 'attendance_pct': 93.7, 'math_score': 77.0, 'reading_score': 72.0, 'final_score': 39.0}

row 6 Before : {'gender': 'male', 'study_hours': nan, 'attendance_pct': 87.1, 'math_score': 95.0, 'reading_score': 78.0, 'final_score': 43.4}
row 6 After : {'gender': 'male', 'study_hours': 3.4, 'attendance_pct': 87.1, 'math_score': 95.0, 'reading_score': 78.0, 'final_score': 43.4}

row 7 Before : {'gender': 'femle', 'study_hours': nan, 'attendance_pct': 70.6, 'math_score': 59.0, 'reading_score': 70.0, 'final_score': 32.8}
row 7 After : {'gender': 'femle', 'study_hours': 3.4, 'attendance_pct': 70.6, 'math_score': 59.0, 'reading_score': 70.0, 'final_score': 32.8}

row 8 Before : {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 74.7, 'math_score': 68.0, 'reading_score': 71.0, 'final_score': 35.3}
row 8 After : {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 74.7, 'math_score': 68.0, 'reading_score': 71.0, 'final_score': 35.3}

row 9 Before : {'gender': 'female', 'study_hours': 4.2, 'attendance_pct': 92.4, 'math_score': 63.0, 'reading_score': 66.0, 'final_score': 35.0}
row 9 After : {'gender': 'female', 'study_hours': 4.2, 'attendance_pct': 92.4, 'math_score': 63.0, 'reading_score': 66.0, 'final_score': 35.0}

row 10 Before : {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 67.9, 'math_score': 94.0, 'reading_score': 73.0, 'final_score': 40.1}
row 10 After : {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 67.9, 'math_score': 94.0, 'reading_score': 73.0, 'final_score': 40.1}

row 11 Before : {'gender': nan, 'study_hours': 4.6, 'attendance_pct': 86.2, 'math_score': 63.0, 'reading_score': 78.0, 'final_score': 36.9}
row 11 After : {'gender': 'Unknown', 'study_hours': 4.6, 'attendance_pct': 86.2, 'math_score': 63.0, 'reading_score': 78.0, 'final_score': 36.9}

row 12 Before : {'gender': 'femle', 'study_hours': nan, 'attendance_pct': 95.0, 'math_score': 59.0, 'reading_score': 92.0, 'final_score': 39.7}
row 12 After : {'gender': 'femle', 'study_hours': 3.4, 'attendance_pct': 95.0, 'math_score': 59.0, 'reading_score': 92.0, 'final_score': 39.7}

row 13 Before : {'gender': 'male', 'study_hours': nan, 'attendance_pct': 86.5, 'math_score': 61.0, 'reading_score': 50.0, 'final_score': 30.8}
row 13 After : {'gender': 'male', 'study_hours': 3.4, 'attendance_pct': 86.5, 'math_score': 61.0, 'reading_score': 50.0, 'final_score': 30.8}

row 14 Before : {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 79.0, 'math_score': 68.0, 'reading_score': 91.0, 'final_score': 39.8}
row 14 After : {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 79.0, 'math_score': 68.0, 'reading_score': 91.0, 'final_score': 39.8}

row 15 Before : {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 76.5, 'math_score': 58.0, 'reading_score': 78.0, 'final_score': 34.9}
row 15 After : {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 76.5, 'math_score': 58.0, 'reading_score': 78.0, 'final_score': 34.9}

row 16 Before : {'gender': 'male', 'study_hours': 2.9, 'attendance_pct': 93.2, 'math_score': 64.0, 'reading_score': 68.0, 'final_score': 35.7}
row 16 After : {'gender': 'male', 'study_hours': 2.9, 'attendance_pct': 93.2, 'math_score': 64.0, 'reading_score': 68.0, 'final_score': 35.7}

row 17 Before : {'gender': 'female', 'study_hours': 3.3, 'attendance_pct': 89.7, 'math_score': 72.0, 'reading_score': 65.0, 'final_score': 36.5}
row 17 After : {'gender': 'female', 'study_hours': 3.3, 'attendance_pct': 89.7, 'math_score': 72.0, 'reading_score': 65.0, 'final_score': 36.5}

row 18 Before : {'gender': 'female', 'study_hours': 2.2, 'attendance_pct': 150.0, 'math_score': 68.0, 'reading_score': 85.0, 'final_score': 45.6}
row 18 After : {'gender': 'female', 'study_hours': 2.2, 'attendance_pct': 150.0, 'math_score': 68.0, 'reading_score': 85.0, 'final_score': 45.6}

row 19 Before : {'gender': 'male', 'study_hours': 2.1, 'attendance_pct': 95.7, 'math_score': 82.0, 'reading_score': 75.0, 'final_score': 41.0}
row 19 After : {'gender': 'male', 'study_hours': 2.1, 'attendance_pct': 95.7, 'math_score': 82.0, 'reading_score': 75.0, 'final_score': 41.0}

row 20 Before : {'gender': 'female', 'study_hours': nan, 'attendance_pct': 93.5, 'math_score': 65.0, 'reading_score': 54.0, 'final_score': 33.1}
row 20 After : {'gender': 'female', 'study_hours': 3.4, 'attendance_pct': 93.5, 'math_score': 65.0, 'reading_score': 54.0, 'final_score': 33.1}

row 21 Before : {'gender': 'male', 'study_hours': 5.1, 'attendance_pct': 102.9, 'math_score': 67.0, 'reading_score': 76.0, 'final_score': 38.9}
row 21 After : {'gender': 'male', 'study_hours': 5.1, 'attendance_pct': 102.9, 'math_score': 67.0, 'reading_score': 76.0, 'final_score': 38.9}

row 22 Before : {'gender': 'male', 'study_hours': 3.4, 'attendance_pct': 90.7, 'math_score': 74.0, 'reading_score': 86.0, 'final_score': 41.0}
row 22 After : {'gender': 'male', 'study_hours': 3.4, 'attendance_pct': 90.7, 'math_score': 74.0, 'reading_score': 86.0, 'final_score': 41.0}

row 23 Before : {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 83.4, 'math_score': 104.0, 'reading_score': 82.0, 'final_score': 45.5}
row 23 After : {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 83.4, 'math_score': 104.0, 'reading_score': 82.0, 'final_score': 45.5}

row 24 Before : {'gender': 'female', 'study_hours': 3.9, 'attendance_pct': 83.6, 'math_score': 58.0, 'reading_score': 64.0, 'final_score': 32.9}
row 24 After : {'gender': 'female', 'study_hours': 3.9, 'attendance_pct': 83.6, 'math_score': 58.0, 'reading_score': 64.0, 'final_score': 32.9}

row 25 Before : {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 65.7, 'math_score': 99.0, 'reading_score': 56.0, 'final_score': 37.5}
row 25 After : {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 65.7, 'math_score': 99.0, 'reading_score': 56.0, 'final_score': 37.5}

row 26 Before : {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 86.5, 'math_score': 52.0, 'reading_score': 68.0, 'final_score': 32.7}
row 26 After : {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 86.5, 'math_score': 52.0, 'reading_score': 68.0, 'final_score': 32.7}

row 27 Before : {'gender': 'female', 'study_hours': 5.3, 'attendance_pct': 84.8, 'math_score': 73.0, 'reading_score': 111.0, 'final_score': 45.4}
row 27 After : {'gender': 'female', 'study_hours': 5.3, 'attendance_pct': 84.8, 'math_score': 73.0, 'reading_score': 111.0, 'final_score': 45.4}

row 28 Before : {'gender': 'female', 'study_hours': nan, 'attendance_pct': 71.7, 'math_score': 65.0, 'reading_score': 53.0, 'final_score': 30.8}
row 28 After : {'gender': 'female', 'study_hours': 3.4, 'attendance_pct': 71.7, 'math_score': 65.0, 'reading_score': 53.0, 'final_score': 30.8}

row 29 Before : {'gender': 'male', 'study_hours': 5.4, 'attendance_pct': 84.7, 'math_score': 58.0, 'reading_score': 62.0, 'final_score': 32.4}
row 29 After : {'gender': 'male', 'study_hours': 5.4, 'attendance_pct': 84.7, 'math_score': 58.0, 'reading_score': 62.0, 'final_score': 32.4}

row 30 Before : {'gender': 'female', 'study_hours': 0.4, 'attendance_pct': 98.4, 'math_score': 80.0, 'reading_score': 77.0, 'final_score': 41.3}
row 30 After : {'gender': 'female', 'study_hours': 0.4, 'attendance_pct': 98.4, 'math_score': 80.0, 'reading_score': 77.0, 'final_score': 41.3}

row 31 Before : {'gender': 'male', 'study_hours': 4.5, 'attendance_pct': 77.7, 'math_score': 79.0, 'reading_score': 71.0, 'final_score': 37.7}
row 31 After : {'gender': 'male', 'study_hours': 4.5, 'attendance_pct': 77.7, 'math_score': 79.0, 'reading_score': 71.0, 'final_score': 37.7}

row 32 Before : {'gender': 'male', 'study_hours': 3.6, 'attendance_pct': 75.4, 'math_score': 63.0, 'reading_score': 70.0, 'final_score': 34.0}
row 32 After : {'gender': 'male', 'study_hours': 3.6, 'attendance_pct': 75.4, 'math_score': 63.0, 'reading_score': 70.0, 'final_score': 34.0}

row 33 Before : {'gender': nan, 'study_hours': nan, 'attendance_pct': 96.0, 'math_score': 39.0, 'reading_score': 96.0, 'final_score': 36.6}
row 33 After : {'gender': 'Unknown', 'study_hours': 3.4, 'attendance_pct': 96.0, 'math_score': 39.0, 'reading_score': 96.0, 'final_score': 36.6}

row 34 Before : {'gender': nan, 'study_hours': 3.6, 'attendance_pct': 91.3, 'math_score': 64.0, 'reading_score': 62.0, 'final_score': 34.2}
row 34 After : {'gender': 'Unknown', 'study_hours': 3.6, 'attendance_pct': 91.3, 'math_score': 64.0, 'reading_score': 62.0, 'final_score': 34.2}

row 35 Before : {'gender': 'femle', 'study_hours': 1.1, 'attendance_pct': 115.6, 'math_score': 72.0, 'reading_score': 72.0, 'final_score': 40.3}
row 35 After : {'gender': 'femle', 'study_hours': 1.1, 'attendance_pct': 115.6, 'math_score': 72.0, 'reading_score': 72.0, 'final_score': 40.3}

row 36 Before : {'gender': 'male', 'study_hours': 3.2, 'attendance_pct': 71.8, 'math_score': 70.0, 'reading_score': 74.0, 'final_score': 36.1}
row 36 After : {'gender': 'male', 'study_hours': 3.2, 'attendance_pct': 71.8, 'math_score': 70.0, 'reading_score': 74.0, 'final_score': 36.1}

row 37 Before : {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 92.2, 'math_score': 81.0, 'reading_score': 62.0, 'final_score': 38.0}
row 37 After : {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 92.2, 'math_score': 81.0, 'reading_score': 62.0, 'final_score': 38.0}

row 38 Before : {'gender': 'female', 'study_hours': 5.3, 'attendance_pct': 88.2, 'math_score': 99.0, 'reading_score': 55.0, 'final_score': 39.6}
row 38 After : {'gender': 'female', 'study_hours': 5.3, 'attendance_pct': 88.2, 'math_score': 99.0, 'reading_score': 55.0, 'final_score': 39.6}

row 39 Before : {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 85.6, 'math_score': 76.0, 'reading_score': 75.0, 'final_score': 38.8}
row 39 After : {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 85.6, 'math_score': 76.0, 'reading_score': 75.0, 'final_score': 38.8}

row 40 Before : {'gender': 'male', 'study_hours': 2.5, 'attendance_pct': 94.1, 'math_score': 79.0, 'reading_score': 94.0, 'final_score': 43.9}
row 40 After : {'gender': 'male', 'study_hours': 2.5, 'attendance_pct': 94.1, 'math_score': 79.0, 'reading_score': 94.0, 'final_score': 43.9}

row 41 Before : {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 84.7, 'math_score': 72.0, 'reading_score': 77.0, 'final_score': 38.3}
row 41 After : {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 84.7, 'math_score': 72.0, 'reading_score': 77.0, 'final_score': 38.3}

row 42 Before : {'gender': 'male', 'study_hours': 4.6, 'attendance_pct': 65.6, 'math_score': 88.0, 'reading_score': 73.0, 'final_score': 38.7}
row 42 After : {'gender': 'male', 'study_hours': 4.6, 'attendance_pct': 65.6, 'math_score': 88.0, 'reading_score': 73.0, 'final_score': 38.7}

row 43 Before : {'gender': nan, 'study_hours': 3.9, 'attendance_pct': 76.5, 'math_score': 78.0, 'reading_score': 73.0, 'final_score': 37.8}
row 43 After : {'gender': 'Unknown', 'study_hours': 3.9, 'attendance_pct': 76.5, 'math_score': 78.0, 'reading_score': 73.0, 'final_score': 37.8}

row 44 Before : {'gender': 'male', 'study_hours': 2.9, 'attendance_pct': 200.0, 'math_score': 81.0, 'reading_score': 69.0, 'final_score': 50.0}
row 44 After : {'gender': 'male', 'study_hours': 2.9, 'attendance_pct': 200.0, 'math_score': 81.0, 'reading_score': 69.0, 'final_score': 50.0}

row 45 Before : {'gender': 'female', 'study_hours': 4.1, 'attendance_pct': 96.7, 'math_score': 97.0, 'reading_score': 86.0, 'final_score': 46.3}
row 45 After : {'gender': 'female', 'study_hours': 4.1, 'attendance_pct': 96.7, 'math_score': 97.0, 'reading_score': 86.0, 'final_score': 46.3}

row 46 Before : {'gender': 'male', 'study_hours': 3.6, 'attendance_pct': 81.3, 'math_score': 73.0, 'reading_score': 66.0, 'final_score': 36.0}
row 46 After : {'gender': 'male', 'study_hours': 3.6, 'attendance_pct': 81.3, 'math_score': 73.0, 'reading_score': 66.0, 'final_score': 36.0}

row 47 Before : {'gender': 'female', 'study_hours': 4.7, 'attendance_pct': 90.0, 'math_score': 66.0, 'reading_score': 56.0, 'final_score': 33.3}
row 47 After : {'gender': 'female', 'study_hours': 4.7, 'attendance_pct': 90.0, 'math_score': 66.0, 'reading_score': 56.0, 'final_score': 33.3}

row 48 Before : {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 112.8, 'math_score': 77.0, 'reading_score': 53.0, 'final_score': 37.2}
row 48 After : {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 112.8, 'math_score': 77.0, 'reading_score': 53.0, 'final_score': 37.2}

row 49 Before : {'gender': 'male', 'study_hours': 3.1, 'attendance_pct': 84.7, 'math_score': 87.0, 'reading_score': 73.0, 'final_score': 40.5}
row 49 After : {'gender': 'male', 'study_hours': 3.1, 'attendance_pct': 84.7, 'math_score': 87.0, 'reading_score': 73.0, 'final_score': 40.5}

row 50 Before : {'gender': nan, 'study_hours': 3.0, 'attendance_pct': 84.9, 'math_score': 78.0, 'reading_score': 85.0, 'final_score': 40.9}
row 50 After : {'gender': 'Unknown', 'study_hours': 3.0, 'attendance_pct': 84.9, 'math_score': 78.0, 'reading_score': 85.0, 'final_score': 40.9}

row 51 Before : {'gender': 'female', 'study_hours': 1.7, 'attendance_pct': 86.9, 'math_score': 86.0, 'reading_score': 75.0, 'final_score': 40.8}
row 51 After : {'gender': 'female', 'study_hours': 1.7, 'attendance_pct': 86.9, 'math_score': 86.0, 'reading_score': 75.0, 'final_score': 40.8}

row 52 Before : {'gender': nan, 'study_hours': 3.9, 'attendance_pct': 91.1, 'math_score': 60.0, 'reading_score': 68.0, 'final_score': 34.7}
row 52 After : {'gender': 'Unknown', 'study_hours': 3.9, 'attendance_pct': 91.1, 'math_score': 60.0, 'reading_score': 68.0, 'final_score': 34.7}

row 53 Before : {'gender': 'femle', 'study_hours': 3.8, 'attendance_pct': 81.5, 'math_score': 57.0, 'reading_score': 78.0, 'final_score': 35.0}
row 53 After : {'gender': 'femle', 'study_hours': 3.8, 'attendance_pct': 81.5, 'math_score': 57.0, 'reading_score': 78.0, 'final_score': 35.0}

row 54 Before : {'gender': 'female', 'study_hours': 3.5, 'attendance_pct': 91.1, 'math_score': 62.0, 'reading_score': 74.0, 'final_score': 36.3}
row 54 After : {'gender': 'female', 'study_hours': 3.5, 'attendance_pct': 91.1, 'math_score': 62.0, 'reading_score': 74.0, 'final_score': 36.3}

row 55 Before : {'gender': nan, 'study_hours': 3.2, 'attendance_pct': 300.0, 'math_score': 51.0, 'reading_score': 82.0, 'final_score': 56.6}
row 55 After : {'gender': 'Unknown', 'study_hours': 3.2, 'attendance_pct': 300.0, 'math_score': 51.0, 'reading_score': 82.0, 'final_score': 56.6}

row 56 Before : {'gender': 'male', 'study_hours': 1.8, 'attendance_pct': 88.4, 'math_score': 72.0, 'reading_score': 88.0, 'final_score': 40.8}
row 56 After : {'gender': 'male', 'study_hours': 1.8, 'attendance_pct': 88.4, 'math_score': 72.0, 'reading_score': 88.0, 'final_score': 40.8}

row 57 Before : {'gender': 'male', 'study_hours': 3.0, 'attendance_pct': 85.5, 'math_score': 64.0, 'reading_score': 61.0, 'final_score': 33.4}
row 57 After : {'gender': 'male', 'study_hours': 3.0, 'attendance_pct': 85.5, 'math_score': 64.0, 'reading_score': 61.0, 'final_score': 33.4}

row 58 Before : {'gender': 'male', 'study_hours': 3.1, 'attendance_pct': 82.8, 'math_score': 88.0, 'reading_score': 44.0, 'final_score': 34.8}
row 58 After : {'gender': 'male', 'study_hours': 3.1, 'attendance_pct': 82.8, 'math_score': 88.0, 'reading_score': 44.0, 'final_score': 34.8}

row 59 Before : {'gender': 'male', 'study_hours': nan, 'attendance_pct': 80.2, 'math_score': 51.0, 'reading_score': 68.0, 'final_score': 31.7}
row 59 After : {'gender': 'male', 'study_hours': 3.4, 'attendance_pct': 80.2, 'math_score': 51.0, 'reading_score': 68.0, 'final_score': 31.7}