## KNN Algorithm in Supervised ML
## KNeighborsClassifier of sklearn library for this one

In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [2]:
X = np.array([
    [1,3500],
    [2,3200],
    [3,3000],
    [4,2500],
    [5,2300],
    [6,2000],
    [7,2200],
    [2,3700]])
y = ['Unfit','Unfit','Unfit','Fit','Fit','Fit','Fit','Unfit']

In [3]:
#Create Model
model=KNeighborsClassifier(n_neighbors=3)

In [4]:
model.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [5]:
#predict
new_person = [[4.5,2600]] #4.5hrs exercise,2600 cal
pred = model.predict(new_person)
print('Predicted Result : ',pred[0])

Predicted Result :  Fit

In [10]:
#prediction from taking the valueas from user
exercise_hours=float(input('Enter Hours of Exercise : '))
cal_intake=float(input('Enter Amount of Calories Consumed'))
pred_fut=model.predict([[exercise_hours,cal_intake]])
print(f'Exercise Hours {exercise_hours}, Calories Intake {cal_intake}, You are likely {pred_fut[0]}')

Enter Hours of Exercise :  5.5
Enter Amount of Calories Consumed 5000

Exercise Hours 5.5, Calories Intake 5000.0, You are likely Unfit

## Example 2

In [11]:
import pandas as pd

In [36]:
df = pd.read_csv('fruit_data.csv')
df

   Weight  Size   Fruit
0     150   7.0   Apple
1     160   7.2   Apple
2     200   8.0  Orange
3     210   8.2  Orange
4     180   7.5     NaN

In [37]:
df.isnull().sum()

Weight    0
Size      0
Fruit     1
dtype: int64

In [38]:
df.dropna(inplace=True)
df

   Weight  Size   Fruit
0     150   7.0   Apple
1     160   7.2   Apple
2     200   8.0  Orange
3     210   8.2  Orange

In [39]:
#split the data
X = df[['Weight','Size']]
y = df['Fruit']

In [40]:
model=KNeighborsClassifier(n_neighbors=3)

In [41]:
model.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [42]:
#base on data provided
new_fruit=pd.DataFrame([[180,7.5]],columns=['Weight','Size'])
pred = model.predict(new_fruit)
print('Perdicted Result : ',pred[0])

Perdicted Result :  Apple

In [43]:
#User input Values
fruit_weight=float(input('Enter Fruit Weight : '))
fruit_size=float(input('Enter Fruit Size : '))
our_fruit=pd.DataFrame([[fruit_weight,fruit_size]],columns=['Weight','Size'])
pred_fruit=model.predict(our_fruit)
print(f' Fruit Weight {fruit_weight}gm, Fruit Size {fruit_size}cm,The fruit is most likely {pred_fruit[0]}')

Enter Fruit Weight :  500
Enter Fruit Size :  8

 Fruit Weight 500.0gm, Fruit Size 8.0cm,The fruit is most likely Orange

## Assignment 1

In [44]:
dv=pd.read_csv('student_grade.csv')

In [45]:
dv

   Hours_Studied  Assignments_Completed Grade
0            1.5                      1     C
1            2.0                      2     C
2            3.0                      3     B
3            4.0                      4     B
4            5.0                      5     A
5            6.0                      6     A

In [46]:
X = dv[['Hours_Studied','Assignments_Completed']]
y = dv['Grade']

In [47]:
model=KNeighborsClassifier(n_neighbors=3)

In [48]:
model.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [51]:
#User input Values
hours_study=float(input('Enter Hours of study : '))
assign_comp=float(input('Enter Assignmment done : '))
result_expect=pd.DataFrame([[hours_study,assign_comp]],columns=['Hours_Studied','Assignments_Completed'])
pred_result=model.predict(result_expect)
print(f' Hours Study {hours_study}, with Assignment {assign_comp} completed, most likely {pred_result[0]}')

Enter Hours of study :  2
Enter Assignmment done :  1

 Hours Study 2.0, with Assignment 1.0 completed, most likely C