# Supervised Machine Learning-Linear Regression

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('sales_data.csv')
data.head()

   Advertising_Spend  Sales_Revenue
0               1000          12000
1               1500          15000
2               2000          18000
3               2500          20000
4               3000          23000

In [3]:
x = data[['Advertising_Spend']]
y = data['Sales_Revenue']

In [4]:
model = LinearRegression()
model.fit(x,y)
print('Training Done')

Training Done

In [17]:
new_spend = int(input('Enter New Spend to Predict Sales Revenue'))
predicted_revenue = model.predict([[new_spend]])
print(f'New Spend {new_spend} Predicted Revenue {predicted_revenue.round(2)}')

Enter New Spend to Predict Sales Revenue 2000

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

AttributeError: 'LinearRegression' object has no attribute 'coef_'

In [18]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [19]:
df=pd.read_csv('sales_data.csv')
df.head(2)

   Advertising_Spend  Sales_Revenue
0               1000          12000
1               1500          15000

In [20]:
adv_spend = data[['Advertising_Spend']]
sales_rev = data['Sales_Revenue']

In [21]:
model=LinearRegression()

In [22]:
model.fit(adv_spend,sales_rev)

LinearRegression()

In [23]:
pr_value=model.predict([[2700]])
print(pr_value)

[21185.71428571]

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [38]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [39]:
dfs=pd.read_csv('house_price.csv')
dfs.head()

   Size_sqft   Price
0       1000  150000
1       1200  170000
2       1500  200000
3       1800  230000
4       2000  260000

In [47]:
sizes=dfs[['Size_sqft']]
prices=dfs['Price']
dfs

   Size_sqft   Price
0       1000  150000
1       1200  170000
2       1500  200000
3       1800  230000
4       2000  260000
5       1700       ?

In [52]:
model=LinearRegression()

In [53]:
model.fit(sizes,prices)

ValueError: could not convert string to float: '?'

In [51]:
price_value=model.predict(pd.DataFrame({'Size_sqft': [1700]}))
print(price_value)

AttributeError: 'LinearRegression' object has no attribute 'coef_'