# 2. Logistic Regression Pass/Fail

In [15]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [16]:
df=pd.read_csv('pass_fail.csv')
display(df)

   Hours Result
0      1   Fail
1      2   Fail
2      3   Fail
3      4   Pass
4      5   Pass
5      6   Pass
6      7   Pass

In [17]:
X =df[['Hours']]
y =df['Result']

In [18]:
model=LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [21]:
pred_35 = model.predict([[3.5]])
print('Predicted result for 3.5 : ',pred_35[0])

Predicted result for 3.5 :  Pass

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [22]:
hours_study=float(input('Numbers of Hours studied'))
pred_value=model.predict([[hours_study]])
print(f'After {hours_study} hours study you are likely to {pred_value[0]}')

Numbers of Hours studied 2

After 2.0 hours study you are likely to Fail

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

## example 2

In [101]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

In [102]:
data = pd.read_csv('customer_purchase.csv')
data

   Age  Salary Purchased
0   22   25000        No
1   25   30000        No
2   30   40000       Yes
3   35   50000       Yes
4   40   60000       Yes

In [103]:
le=LabelEncoder()
data['Purchased'] = le.fit_transform(data['Purchased'])
X = data[['Age','Salary']]
y = data['Purchased']
data

   Age  Salary  Purchased
0   22   25000          0
1   25   30000          0
2   30   40000          1
3   35   50000          1
4   40   60000          1

In [104]:
model=LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [105]:
#predict the result
new_customer = [[28, 35000]]
prediction = model.predict(new_customer)
print(f"Predicted Result (1=Yes, 0=No): {prediction[0]}")

Predicted Result (1=Yes, 0=No): 1

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [106]:
new_cust_age=int(input('Enter Age : '))
new_cust_sal=int(input('Enter Salary : '))
new_customer=[[new_cust_age,new_cust_sal]]
prediction=model.predict(new_customer)
if (prediction):
    print('Purchased')
else :
    print('Not Purchased')

Enter Age :  50
Enter Salary :  55000

Purchased

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

## Exercise 1

In [107]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer

In [77]:
dls = pd.read_csv('spam_dataset.csv')
dls.head()

                                     message_content  is_spam
0  Hello Lonnie,\n\nJust wanted to touch base reg...        0
1  Congratulations, you've won a prize! Call us n...        1
2  You have been pre-approved for a credit card w...        1
3  Limited time offer, act now! Only a few spots ...        1
4  Your loan has been approved! Transfer funds to...        1

In [78]:
dls.isnull().sum()

message_content    0
is_spam            0
dtype: int64

In [91]:
cv=CountVectorizer()

In [92]:
X = cv.fit_transform(dls[['message_content']])
y = dls['is_spam']

In [97]:
model = LogisticRegression()

In [98]:
model.fit(X,y)

ValueError: Found input variables with inconsistent numbers of samples: [1, 1000]

In [96]:
new_msg=input('Enter your email here : \n')
new_msg_CV=cv.transform([new_msg])
predict_spam=model.predict(new_sg_CV)
if (predict_spam):
    print('This is spam message')
else :
    print('This is not a spam message')

Enter your email here :
 you win an iphone

NameError: name 'new_sg_CV' is not defined