# This is Pandas example to read out from an Excel file

In [31]:
import pandas as pd

In [32]:
df=pd.read_excel("students.xlsx")

In [33]:
print('Print data as follow')
df

Print data as follow

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   Nick   21     59
5  Nancy   20     90

In [34]:
dfpatients=pd.read_csv('C:/Users/User/AIML/Day-10/patients.csv')

In [35]:
dfpatients

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76
...,...,...,...,...,...,...,...
995,PAT-a01bf534,Amber Vang,26,2025-12-02,2025-12-04,emergency,91
996,PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
999,PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83

In [36]:
dfpatients['name']

0      Richard Rodriguez
1         Shannon Walker
2           Julia Torres
3        Crystal Johnson
4            Garrett Lin
             ...
995           Amber Vang
996         Martha Smith
997       Jennifer James
998       Kara Hernandez
999      Lorraine Turner
Name: name, Length: 1000, dtype: object

In [37]:
display(dfpatients['name'])

0      Richard Rodriguez
1         Shannon Walker
2           Julia Torres
3        Crystal Johnson
4            Garrett Lin
             ...
995           Amber Vang
996         Martha Smith
997       Jennifer James
998       Kara Hernandez
999      Lorraine Turner
Name: name, Length: 1000, dtype: object

## Head in dataframe

In [38]:
dfpatients.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

In [39]:
dfpatients.head(2)

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83

In [40]:
df.head()

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   Nick   21     59

In [41]:
df.head(3)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78

## Tail example

In [42]:
print("Last two students from excel sheet")
df.tail(2)

Last two students from excel sheet

    Name  Age  Marks
4   Nick   21     59
5  Nancy   20     90

In [43]:
print("Last 5 patients from csv sheet")
dfpatients.tail(4)

Last 5 patients from csv sheet

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
996,PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
999,PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83

## Shape example will return you (rows,columns)

In [44]:
dfpatients.shape

(1000, 7)

In [45]:
df.shape

(6, 3)

In [49]:
r,c=dfpatients.shape
print(f'rows: {r}, columns : {c}')

rows: 1000,columns : 7

In [50]:
r,c=df.shape
print(f'rows: {r}, columns : {c}')

rows: 6, columns : 3

## Values in Dataframe

In [52]:
print('Students values')
df.values

Students values

array([['John', 20, 85],
       ['Alice', 22, 90],
       ['Bob', 21, 78],
       ['Sara', 23, 92],
       ['Nick', 21, 59],
       ['Nancy', 20, 90]], dtype=object)

In [53]:
print('Patients Values')
dfpatients.values

Patients Values

array([['PAT-09484753', 'Richard Rodriguez', 24, ..., '2025-03-22',
        'surgery', 61],
       ['PAT-f0644084', 'Shannon Walker', 6, ..., '2025-12-14',
        'surgery', 83],
       ['PAT-ac6162e4', 'Julia Torres', 24, ..., '2025-07-05',
        'general_medicine', 83],
       ...,
       ['PAT-8f07e894', 'Jennifer James', 72, ..., '2025-12-21', 'ICU',
        69],
       ['PAT-4ae301e1', 'Kara Hernandez', 47, ..., '2025-02-20', 'ICU',
        61],
       ['PAT-e2ef9c5f', 'Lorraine Turner', 64, ..., '2025-05-08',
        'general_medicine', 83]], dtype=object)