In [ ]:
import pandas as pd
import re
import string
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from sklearn.linear_model import LogisticRegression
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [ ]:
data={'message': [
        "Win a brand new car! Text WIN to 99999 now!",
        "Hi John, are we meeting today?",
        "Exclusive offer just for you. Claim your free prize!",
        "Please call me when you reach office.",
        "Limited-time deal! Buy 1 get 1 free now!",
        "Can you send me the report by evening?",
        "You have been selected for a $1000 gift card!",
        "Lunch at 1 pm?",
        "Congratulations! You’ve won free tickets to Maldives!",
        "Hey, don't forget about the meeting tomorrow."
    ],
    'label': [
        "Spam", "Valid", "Spam", "Valid", "Spam",
        "Valid", "Spam", "Valid", "Spam", "Valid"
    ]
}

In [ ]:
df = pd.DataFrame(data)
df

                                             message  label
0        Win a brand new car! Text WIN to 99999 now!   Spam
1                     Hi John, are we meeting today?  Valid
2  Exclusive offer just for you. Claim your free ...   Spam
3              Please call me when you reach office.  Valid
4           Limited-time deal! Buy 1 get 1 free now!   Spam
5             Can you send me the report by evening?  Valid
6      You have been selected for a $1000 gift card!   Spam
7                                     Lunch at 1 pm?  Valid
8  Congratulations! You’ve won free tickets to Ma...   Spam
9      Hey, don't forget about the meeting tomorrow.  Valid

In [ ]:
def clean_text(text) :
  text=text.lower()
  text=re.sub(r"http\S+","",text)
  text=re.sub(r"www\S+","",text)
  text=re.sub(r"[^a-z\s]","",text)
  text="".join([word for word in text.split() if word not in stopwords.words("english")])
  return text

In [ ]:
df["clean_message"]=df["message"].apply(clean_text)
df["clean_message"]

0                      winbrandnewcartextwin
1                         hijohnmeetingtoday
2               exclusiveofferclaimfreeprize
3                      pleasecallreachoffice
4                  limitedtimedealbuygetfree
5                          sendreportevening
6                           selectedgiftcard
7                                    lunchpm
8    congratulationsyouvefreeticketsmaldives
9               heydontforgetmeetingtomorrow
Name: clean_message, dtype: object

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df["clean_message"],df["label"],test_size=0.2,random_state=42)

In [ ]:
vectorizer=CountVectorizer()
X_train_vec=vectorizer.fit_transform(X_train)
X_test_vec=vectorizer.transform(X_test)

In [ ]:
model=MultinomialNB()
model.fit(X_train_vec,y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(X_test_vec)
acc = accuracy_score(y_test, y_pred)
cnf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Accuracy:", acc)
print("Confusion Matrix:\n", cnf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.5
Confusion Matrix:
 [[1 0]
 [1 0]]
Classification Report:
               precision    recall  f1-score   support

        Spam       0.50      1.00      0.67         1
       Valid       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
new_msg=[
    "Free! Free! entry in our draw of RM3000 prize! Click Now!! Offer Only for Limited Time!!!",
    "Let's go for a party this weekend",
    "Remainder: Teams meeting going to start with in 10 minutes.",
    "Hey, don't forget about the meeting tomorrow.",
    "Congratulations! You’ve won free tickets to Maldives"
]
new_clean_msg = [clean_text(msg) for msg in new_msg]
new_clean_msg_vec = vectorizer.transform(new_clean_msg)
predictions = model.predict(new_clean_msg_vec)
print("\n Prediction :")
for msg,prediction in zip(new_msg,predictions):
  print(f"{msg} --> {prediction}")

 Prediction :
Free! Free! entry in our draw of RM3000 prize! Click Now!! Offer Only for Limited Time!!! --> Spam
Let's go for a party this weekend --> Spam
Remainder: Teams meeting going to start with in 10 minutes. --> Spam
Hey, don't forget about the meeting tomorrow. --> Valid
Congratulations! You’ve won free tickets to Maldives --> Spam

**Exercise : 1 (NLP) Day26**
*   Use the resume set from kaggle and do the following task:
1.   Load the dataset
2.   Clean the text
3.   Convert Text to Features using TFIDF
4.   Train a simple multiclass mode of your choice to predict resume category.
5.   Evaluate the result

In [ ]:
resume_data=pd.read_csv("/content/sample_data/UpdatedResumeDataSet.csv")
print(resume_data.shape)
resume_data.head(20)

(962, 2)

        Category                                             Resume
0   Data Science  Skills * Programming Languages: Python (pandas...
1   Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2   Data Science  Areas of Interest Deep Learning, Control Syste...
3   Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4   Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...
5   Data Science  SKILLS C Basics, IOT, Python, MATLAB, Data Sci...
6   Data Science  Skills â¢ Python â¢ Tableau â¢ Data Visuali...
7   Data Science  Education Details \r\n B.Tech   Rayat and Bahr...
8   Data Science  Personal Skills â¢ Ability to quickly grasp t...
9   Data Science  Expertise â Data and Quantitative Analysis â...
10  Data Science  Skills * Programming Languages: Python (pandas...
11  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
12  Data Science  Areas of Interest Deep Learning, Control Syste...
13  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
14  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...
15  Data Science  SKILLS C Basics, IOT, Python, MATLAB, Data Sci...
16  Data Science  Skills â¢ Python â¢ Tableau â¢ Data Visuali...
17  Data Science  Education Details \r\n B.Tech   Rayat and Bahr...
18  Data Science  Personal Skills â¢ Ability to quickly grasp t...
19  Data Science  Expertise â Data and Quantitative Analysis â...

In [ ]:
def clean_text(text) :
  text=text.lower()
  text=re.sub(r"http\S+","",text)
  text=re.sub(r"www\S+","",text)
  text=re.sub(r"\s+[a-zA-Z]\s+"," ",text)
  text=text.translate(str.maketrans("","",string.punctuation))
  text=re.sub(r"\s+"," ",text)
  text=re.sub(r"[^\x00-\x7f]","",text)
  text="".join([word for word in text.split() if word not in stopwords.words("english")])
  return text

In [ ]:
resume_data["clean_message"]=resume_data["Resume"].apply(clean_text)
resume_data["clean_message"]

0      skillsprogramminglanguagespythonpandasnumpysci...
1      educationdetailsmay2013may2017uitrgpvdatascien...
2      areasinterestdeeplearningcontrolsystemdesignpr...
3      skillspythonsaphanatableausaphanasqlsaphanapal...
4      educationdetailsmcaymcaustfaridabadharyanadata...
                             ...
957    computerskillsproficientmsofficewordbasicexcel...
958    willingnessacceptchallengespositivethinkinggoo...
959    personalskillsquicklearnereagernesslearnnewthi...
960    computerskillssoftwareknowledgemspowerpointmso...
961    skillsetoswindowsxp788110databasemysqlsqlserve...
Name: clean_message, Length: 962, dtype: object

In [ ]:
le=LabelEncoder()
resume_data["Category"]=le.fit_transform(resume_data["Category"])
X=resume_data["clean_message"]
y=resume_data["Category"]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
# Convert Text to feature using Tfidf
vectorize=TfidfVectorizer(max_features=15000, stop_words='english', sublinear_tf=True)
X_train_tfidf=vectorize.fit_transform(X_train)
X_test_tfidf=vectorize.transform(X_test)
print(X_train_tfidf.shape)
X_train_tfidf

(769, 164)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 769 stored elements and shape (769, 164)>

In [ ]:
#Training Model
model_resume=LogisticRegression(multi_class="ovr",max_iter=1000)
model_resume.fit(X_train_tfidf,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(max_iter=1000, multi_class='ovr')

In [ ]:
y_predict = model_resume.predict(X_test_tfidf)
acc = accuracy_score(y_test, y_predict)
cnf_matrix = confusion_matrix(y_test, y_predict)
class_report = classification_report(y_test, y_predict)
print("Accuracy:", acc)
print("Confusion Matrix:\n", cnf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.9637305699481865
Confusion Matrix:
 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0
   0]
 [ 0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 16
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   5]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         5
           3       1.00      1.00      1.00         7
           4       1.00      1.00      1.00         4
           5       1.00      0.67      0.80         9
           6       1.00      1.00      1.00         5
           7       1.00      1.00      1.00         8
           8       1.00      0.93      0.96        14
           9       1.00      1.00      1.00         5
          10       1.00      1.00      1.00         7
          11       1.00      1.00      1.00         6
          12       1.00      1.00      1.00        12
          13       1.00      1.00      1.00         4
          14       1.00      1.00      1.00         7
          15       0.68      1.00      0.81        15
          16       1.00      1.00      1.00         8
          17       1.00      1.00      1.00         3
          18       1.00      1.00      1.00        12
          19       1.00      1.00      1.00         7
          20       1.00      1.00      1.00        10
          21       1.00      1.00      1.00         7
          22       1.00      1.00      1.00         8
          23       1.00      1.00      1.00        16
          24       1.00      1.00      1.00         5

    accuracy                           0.96       193
   macro avg       0.95      0.94      0.94       193
weighted avg       0.96      0.96      0.96       193

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
new_resume=[
    "Skills â¢ Python â¢ Tableau â¢ Data Visualization",
    # "Let's go for a party this weekend",
    # "Remainder: Teams meeting going to start with in 10 minutes.",
    # "Hey, don't forget about the meeting tomorrow.",
    # "Congratulations! You’ve won free tickets to Maldives"
]
new_clean_resume = [clean_text(msg) for msg in new_resume]
new_clean_resume_vec = vectorizer.transform(new_clean_resume)
cat_prediction = model_resume.predict(new_clean_resume_vec)
print("\n Prediction :")
for msg,cat_prediction in zip(new_resume,cat_prediction):
  print(f"{msg} --> {cat_prediction}")

ValueError: X has 8 features, but LogisticRegression is expecting 164 features as input.